apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: firefox-api-proxy
  description: "Firefox Back End For Front End (BFF) Proxy Stable API"
  annotations:
    github.com/project-slug: pocket/firefox-api-proxy
    github.com/team-slug: "backend"
    circleci.com/project-slug: github/pocket/firefox-api-proxy
    sentry.io/project-slug: "firefoxapiproxy"
  links:
    - url: https://firefox-api-proxy.readitlater.com/
      title: Firefox API Proxy (Production)
      icon: collections
    - url: https://firefox-api-proxy.getpocket.dev/
      title: Firefox API Proxy (Dev)
      icon: collections
spec:
  type: service
  owner: backend
  lifecycle: production
  consumesApis:
    - client-api
  providesApis:
    - firefox-api-proxy

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: firefox-dev-api
  description: "Firefox Back End For Front End (BFF) Proxy Stable API"
spec:
  type: rest
  owner: backend
  definition: |
    https://github.com/Pocket/firefox-api-proxy/blob/main/openapi.yml
  lifecycle: production